### ISSUE TITLE
Feature: Custom token adding

### ISSUE THREAD

**Issue by andre-meyer** [gnosis/safe-cmm-app-react#102]
# Description
TBD

**Comment by andre-meyer** [comment]
@alfetopito to research if the safe provides information about custom tokens that were added to the safe assets

**Comment by alfetopito** [comment]
Slack thread https://gnosisinc.slack.com/archives/C63LQTGNB/p1602085170052100

There's no way to get tokens that has just been added to the Safe UI at the moment.

Possibly related to this feature request, though https://github.com/gnosis/safe-apps-sdk/issues/44
