### ISSUE TITLE
Bug: Critical - Withdraw Requests not correctly discovered (not allowing claim)

### ISSUE THREAD

**Issue by andre-meyer** [gnosis/safe-cmm-app-react#105]
# Description

# To Reproduce:

# Expected Behaviour
After a withdrawRequest (and 5min later) the withdrawClaim should be available.

# Actual Behaviour
withdrawRequest was not available and the console indicates that there was no request. Further inspection shows otherwise though. See this deployment:
https://etherscan.io/tx/0x22546afa17518602ab47f49e61d3d4ff70888beeaabeef54773407b1fac3c780#eventlog

# Screenshots/Videos
![image](https://user-images.githubusercontent.com/969493/95483718-e01e7d80-098f-11eb-8283-e7a9cdf48999.png)

# Environment
**Desktop:** *(Please complete)*

# Background

**Comment by alfetopito** [comment]
Close by #108
