### ISSUE TITLE
Bug: Market price is not calculated

### ISSUE THREAD

**Issue by elena-zh** [gnosis/safe-cmm-app-react#122]
# Description
When I select any tokens pair, each time I get an infinity price

# Expected Behaviour
A price should be calculated

# Screenshots/Videos
![image](https://user-images.githubusercontent.com/70885163/96124842-42c9c900-0efc-11eb-94e0-3b5c7144fcf8.png)

# Environment
**Desktop:** 
 - OS: Win 10
 - Browser Chrome, Brave, FF
 - Version  190109794 - 9f55491f128a07fc366b9e944310f9153adb79ba

**Comment by alfetopito** [comment]
DevOps will check tomorrow the CORS issue, which is likely related to infra.

Regardless of that, the UI should handle the failure gracefully and inform the user somehow the price could not be fetched.

**Comment by elena-zh** [comment]
> DevOps will check tomorrow the CORS issue, which is likely related to infra.
> 
> Regardless of that, the UI should handle the failure gracefully and inform the user somehow the price could not be fetched.

Yes, I think that it will be implemented in #93
