### ISSUE TITLE
Lowest price is orange

### ISSUE THREAD

**Issue by c3rnst** [gnosis/safe-cmm-app-react#135]

**Comment by c3rnst** [comment]
<img width="543" alt="Screenshot 2020-10-28 at 14 05 06" src="https://user-images.githubusercontent.com/34367524/97439748-de106480-1926-11eb-884a-124af2a2c685.png">

Even though the price is correctly input, it does not update from the orange). ONLY happens on lowest price (but happens frequently)

**Comment by alfetopito** [comment]
That's on me :sweat_smile: 

Remember the warnings I'll some day hopefully start working on?

Yeah, this is a single warning placeholder that lights up when lowest price < 1 :)

**Comment by alfetopito** [comment]
Addressed on #149
