### ISSUE TITLE
xDAI is not working on Deployment 0.3 (see version screenshot). Deployment fails on multiple issues.

### ISSUE THREAD

**Issue by c3rnst** [gnosis/safe-cmm-app-react#136]

**Comment by c3rnst** [comment]
<img width="1435" alt="Screenshot 2020-10-28 at 14 15 50" src="https://user-images.githubusercontent.com/34367524/97440770-31cf7d80-1928-11eb-9157-e42dbbc419a9.png">
<img width="1420" alt="Screenshot 2020-10-28 at 14 12 59" src="https://user-images.githubusercontent.com/34367524/97440791-385df500-1928-11eb-85b1-fe4f60e5f427.png">

<img width="1424" alt="Screenshot 2020-10-28 at 14 17 23" src="https://user-images.githubusercontent.com/34367524/97440917-65120c80-1928-11eb-8e3f-0651f7a08995.png">

Please see failures based on screenshot.

**Comment by andre-meyer** [comment]
Outdated. Write new ticket if issue persists
