### ISSUE TITLE
Tokens show twice in the drop down of "deploy strategy"

### ISSUE THREAD

**Issue by c3rnst** [gnosis/safe-cmm-app-react#137]

**Comment by c3rnst** [comment]
As you can see attached, I can see USDT twice. I had to wait for a long time to load the second USDT, which has zero balance. 
My assumption is that there is a different one from my Safe and the one that is added to GP? It loads the 50k one as I have it in my Safe and the other one as it's on GP?

<img width="1440" alt="Screenshot 2020-10-28 at 14 23 05" src="https://user-images.githubusercontent.com/34367524/97442035-b1118100-1929-11eb-9e5c-b9a586685124.png">
<img width="1427" alt="Screenshot 2020-10-28 at 14 25 17" src="https://user-images.githubusercontent.com/34367524/97442039-b1aa1780-1929-11eb-8f60-979baa589003.png">
<img width="1426" alt="Screenshot 2020-10-28 at 14 25 24" src="https://user-images.githubusercontent.com/34367524/97442040-b242ae00-1929-11eb-9707-4b666c208fc3.png">

<img width="1440" alt="Screenshot 2020-10-28 at 14 21 04" src="https://user-images.githubusercontent.com/34367524/97442020-ad7dfa00-1929-11eb-9b58-ffe21340bb79.png">

**Comment by alfetopito** [comment]
You also have 2 OWL tokens o.O.

Anyway, listing tokens twice shouldn't happen. Do you see this often?

**Comment by alfetopito** [comment]
Token loading behaviour has been addressed.
Re-open if you still see this.
