### ISSUE TITLE
Loading tokens in deploy strategy is time-delayed for some of them

### ISSUE THREAD

**Issue by c3rnst** [gnosis/safe-cmm-app-react#138]

**Comment by c3rnst** [comment]
See these two screenshots, they are taken a few minutes apart (ca. 45 seconds are needed). Another USDT and PAX are loaded much later to the list of tokens that is available right away (after an initial waiting). 
<img width="1440" alt="Screenshot 2020-10-28 at 14 34 29" src="https://user-images.githubusercontent.com/34367524/97443383-3cd7dd00-192b-11eb-9354-86d4698049d1.png">
<img width="1440" alt="Screenshot 2020-10-28 at 14 37 26" src="https://user-images.githubusercontent.com/34367524/97443398-4103fa80-192b-11eb-95eb-63ec90fd766d.png">

**Comment by alfetopito** [comment]
As discussed, this is due to how tokens from hardcoded list is loaded after the refactor.
I'll address this according to the priorities (after foldout, after warnings)

**Comment by alfetopito** [comment]
Addressed in #156
