### ISSUE TITLE
Token display in deploy screen disappear

### ISSUE THREAD

**Issue by c3rnst** [gnosis/safe-cmm-app-react#142]

**Comment by c3rnst** [comment]
First the token list loaded (not USDT and PAX). Then I clicked OWL, then the entire list disappeared and only USDT and PAX are shown.
As you can see, I had selected OWL but it is not shown (other than in my available Safe balance). 

![Screenshot 2020-10-29 at 10 28 41](https://user-images.githubusercontent.com/34367524/97550370-e4a7e600-19d1-11eb-9ec3-bf31df3bf325.png)
![Screenshot 2020-10-29 at 10 28 53](https://user-images.githubusercontent.com/34367524/97550376-e70a4000-19d1-11eb-8dbb-664364d294e2.png)

Version 0.2.1. master 194669939 - 012739

**Comment by alfetopito** [comment]
Loading behaviour has been addressed.
Re-open if still happens.
