### ISSUE TITLE
Feature: Refresh data on new block

### ISSUE THREAD

**Issue by alfetopito** [gnosis/safe-cmm-app-react#178]
# Description

Refresh blockchain data on every new block.

We currently have a workaround to update data on the background at every fixed amount of time (~30s).
That's not ideal as it doesn't synchronize with data coming from the network

# Requirements
- [ ] Subscribe to network changes
- [ ] Update dependent state upon new block headers

# Background

For reference, check how Mesa does the subscription

**Comment by andre-meyer** [comment]
Related to #217

**Comment by andre-meyer** [comment]
# Requirements
- [ ] Remove all `interval` uses
