### ISSUE TITLE
Bug: links are not working

### ISSUE THREAD

**Issue by c3rnst** [gnosis/safe-cmm-app-react#180]

**Comment by c3rnst** [comment]
![Screenshot 2020-11-30 at 11 18 55](https://user-images.githubusercontent.com/34367524/100597696-0c0a0f80-32fe-11eb-874f-00cb91f66af7.png)

1. Link to Gnosis Protocol Dex is not working on first screen, let's use https://gnosis.io/protocol/
2. Link toRead the docs is not working: https://docs.gnosis.io/protocol/docs/intro-cmm/ 
3. on first screen let's have the buttons "Next" (not Start, which is misleading and should be only on the last modal)
4. the dots are not clickable. 
5. Last screen. instead of finish, use "Start" (was Michel's suggestion, right)? 
6. For discord link, use: https://chat.gnosis.io/ (not the invite link) - maybe it changes immediately (also possible)...

**Comment by c3rnst** [comment]
This modal re-appears every time. 
Shall we copy the function from the withdrawl modal and allow the user to choose "Do not show modal again"?

**Comment by andre-meyer** [comment]
It would stop reappearing if you went through all screens :D @c3rnst It only sets the flag once all screen were read. Should this be changed so that it's only ever shown once or would you rather have the checkbox?

**Comment by c3rnst** [comment]
Hahaha that makes sense. I did indeed not click on the last page but went for the "x" to see if that worked. Ha. This is not a priority - let's copy the "do not show modal again" from the withdraw flow after the release!
