### ISSUE TITLE
Unclear bracket overview

### ISSUE THREAD

**Issue by c3rnst** [gnosis/safe-cmm-app-react#181]

**Comment by c3rnst** [comment]
I find this a bit confusing. Based on this screenshot, I have 0 xOWL, though it says xOWL- 4 brackets...

![Screenshot 2020-11-30 at 11 31 02](https://user-images.githubusercontent.com/34367524/100599328-2ba23780-3300-11eb-8473-385787a3cfcb.png)

**Comment by andre-meyer** [comment]
Fix by removing the Token Symbol/Name next to the bracket count
