### ISSUE TITLE
Withdrawl modals design

### ISSUE THREAD

**Issue by c3rnst** [gnosis/safe-cmm-app-react#183]

**Comment by c3rnst** [comment]
First screen: 
- A space needed between "at least"
- I would get rid of the "at least" - we made it to be 5 Minutes exactly, right? because that's the max?
- claim transaction (transaction does not need to be capitalised)
 - can we use the font as per design?

**Comment by alfetopito** [comment]
Fixed 1 and 2 by removing `at least`.

3 is what the button looks like. I'll leave it as is for now.
![screenshot_2020-11-30_10-37-12](https://user-images.githubusercontent.com/43217/100649853-e7ab3480-32f7-11eb-9ffd-0f0976065939.png)

4: Yes

**Comment by alfetopito** [comment]
For reference, current (non Safe) font
![screenshot_2020-11-30_10-47-07](https://user-images.githubusercontent.com/43217/100650885-79677180-32f9-11eb-97a0-0190a9a4d07d.png)

**Comment by alfetopito** [comment]
After:
![screenshot_2020-11-30_12-34-48](https://user-images.githubusercontent.com/43217/100661461-57292000-3308-11eb-9fa3-d4b7925df613.png)
