### ISSUE TITLE
Closed tab still shows TODO

### ISSUE THREAD

**Issue by c3rnst** [gnosis/safe-cmm-app-react#184]
![Screenshot 2020-11-30 at 12 06 03](https://user-images.githubusercontent.com/34367524/100603067-edf3dd80-3304-11eb-87a2-2416c716d661.png)
If difficult to add: let's leave it

Could we show which of the strategies has the claimable balance?

**Comment by alfetopito** [comment]
Has been addressed on #195 and #196
