### ISSUE TITLE
Bug: Yellow warning on lowest price does not disappear.

### ISSUE THREAD

**Issue by c3rnst** [gnosis/safe-cmm-app-react#185]

**Comment by c3rnst** [comment]
I think we had this issue before?

![Screenshot 2020-11-30 at 12 14 23](https://user-images.githubusercontent.com/34367524/100603924-17f9cf80-3306-11eb-82f3-d19c8efde742.png)

**Comment by alfetopito** [comment]
Same as https://github.com/gnosis/safe-cmm-app-react/issues/189#issuecomment-736074897

**Comment by alfetopito** [comment]
Just tried on staging. All good.
