### ISSUE TITLE
xDai: no market price is shown

### ISSUE THREAD

**Issue by c3rnst** [gnosis/safe-cmm-app-react#189]

**Comment by c3rnst** [comment]
Apologies if this is a replication, I thought I had already included it:

![Screenshot 2020-11-30 at 12 18 36](https://user-images.githubusercontent.com/34367524/100615020-4cc25280-3317-11eb-83d0-d30d49a58b30.png)

Market price is not shown (though we take it from GP and later there is a hold value, so we should have a value)?

We should also have a text for when there is none (I think this exists in the design). 

maybe the loading took too long?

**Comment by alfetopito** [comment]
Using development version. Can't reproduce
![screenshot_2020-11-30_13-45-08](https://user-images.githubusercontent.com/43217/100669423-3960b880-3312-11eb-983f-0e3f770c61af.png)

**Comment by alfetopito** [comment]
Tried on staging, all good.
