### ISSUE TITLE
Feature: "Work in Progress" for missing features

### ISSUE THREAD

**Issue by andre-meyer** [gnosis/safe-cmm-app-react#192]
# Description
Instead of TODO, show a nicer "work in progress"

# Requirements
/

# Background
/

**Comment by alfetopito** [comment]
For Trades, I propose:
![screenshot_2020-11-30_13-55-54](https://user-images.githubusercontent.com/43217/100670505-d112d680-3313-11eb-9204-00cd4372df68.png)

Can't recall the sentence suggested during the meeting.

**Comment by alfetopito** [comment]
For closed strategies:
![screenshot_2020-11-30_14-02-19](https://user-images.githubusercontent.com/43217/100671015-978e9b00-3314-11eb-8ba9-a4410d9c5c49.png)

**Comment by alfetopito** [comment]
Pending strategy fold out
![screenshot_2020-11-30_14-09-22](https://user-images.githubusercontent.com/43217/100671566-91e58500-3315-11eb-9181-5867e3ab52f7.png)

**Comment by alfetopito** [comment]
Hiding `Total Value Claimable` completely for now
![screenshot_2020-11-30_14-20-55](https://user-images.githubusercontent.com/43217/100672715-30beb100-3317-11eb-91bc-599f00e8270b.png)
