### ISSUE TITLE
Bug: Add Min/Max to bracket amount

### ISSUE THREAD

**Issue by andre-meyer** [gnosis/safe-cmm-app-react#222]
# Description
On the Strategy Deploy page, add the HTML attributes for `min` (as 1) and `max` (as 10) on the input to determine the amount of brackets to deploy, so users can't use the button to select invalid values.

**Comment by alfetopito** [comment]
Sent PR to `safe-react-components` so we can have `min` and `max` values https://github.com/gnosis/safe-react-components/pull/80
