### ISSUE TITLE
Feature: Deployment Form Validation

### ISSUE THREAD

**Issue by andre-meyer** [gnosis/safe-cmm-app-react#29]
# Description
This ticket is a separate ticket to track implementation of validations, checks and warnings for the deployment form seen here:

![image](https://user-images.githubusercontent.com/969493/92741763-3f807200-f37f-11ea-8829-16f7257956d5.png)

# Requirements
Please find all texts that are needed in the design.

- [x] Warnings
  - [x] Starting price is off by >2%
  - [x] 1 Bracket selected
  - [x] Only one token will be funded
  - [x] Min Bracket Funding >5k in USD (see code section)
- [x] Errors
  - [x] Insufficient Balance for selected Token
  - [x] Any value == 0 (Funding A, Funding B, Lower Price, Upper Price)
  - [x] Bracketcount must be >0
  - [x] Token A !== Token B

# Code

USD conversion is available via dex-liquidity-provision

**Comment by alfetopito** [comment]
Be aware only partially done. Warnings still missing. Think might be worth to create a new issue for it.

**Comment by andre-meyer** [comment]
Reopen to track progress on warnings

**Comment by andre-meyer** [comment]
4 Day estimation
