### ISSUE TITLE
Feature: Pending Strategy discovery, discovery of signer-count

### ISSUE THREAD

**Issue by andre-meyer** [gnosis/safe-cmm-app-react#34]
# Description
In order to implement the pending screen, we need to discover the pending strategies that are currently waiting to be signed by other owners. This should be fetched from the corresponding API endpoint for the Safe that is used, as it can report pending transactions there.

# Requirements
- [x] Find unconfirmed transactions and be able to decode their parameters:
  - [ ] Funding
  - [x] Creator
  - [x] Date of creation
  - [x] Token pairs used
  - [x] Bracket count

# Code/Background
Multiple different methods need to be tested, it might be possible to "simulate" the decoded data of the transactions, in order to see which events would be emitted and use a similar structure to what is used to handle the on-chain strategies.

**Comment by andre-meyer** [comment]
Close for now. Signer count information tbd

**Comment by elena-zh** [comment]
Verified. A strategy appears in the Pending tab until all the owners confirm/reject it. 
Several cases to consider are found (see the comment [here](https://github.com/gnosis/safe-cmm-app-react/pull/61#issuecomment-707062443))
