### ISSUE TITLE
Bug: Inverted Price Feed

### ISSUE THREAD

**Issue by bh2smith** [gnosis/safe-cmm-app-react#35]
While clicking through the rinkeby version it seems makes the most sense to invert the price feed - depicted in the screenshot below since the left token would usually be stable and the right token is usually volatile. That is, when deploying `DAI-ETH`, the user would expect to see the target price as the value of ETH in DAI

<img width="549" alt="Screenshot 2020-09-07 at 4 48 07 PM" src="https://user-images.githubusercontent.com/11778116/92462161-65184a80-f1ca-11ea-8f14-295bcd2e8001.png">

**Comment by andre-meyer** [comment]
Fixed by https://github.com/gnosis/safe-cmm-app-react/commit/a6373bdb0e6c89a2c688529e70cb6f5e9ac2a0d7#diff-c15642f814ae3797422fa1a4f14e542bR111

(Test with someone who understands prices)

**Comment by bh2smith** [comment]
So then, can this be closed? Or is that not yet merged?

**Comment by andre-meyer** [comment]
I’ll need to verify it but it should be fine now. Can you see the change on dev?

**Comment by bh2smith** [comment]
If by "dev" you mean the current interface then yes! I will close this then. If there is some PR associated with this fix, it would be nice if we could include a link to it here.

<img width="562" alt="Screenshot 2020-09-14 at 9 32 18 AM" src="https://user-
images.githubusercontent.com/11778116/93056768-03bc1400-f6c1-11ea-9491-3fd46ffc83d4.png">
