### ISSUE TITLE
Feature: Strategy Overview

### ISSUE THREAD

**Issue by andre-meyer** [gnosis/safe-cmm-app-react#4]
# Description
*As a user of the CMM App, I want to see an overview of my strategies, so that I can see their details and progress*

# Requirements
- [x] Implement view of active strategies
- [x] Implement a tab-view to change between various other strategy types (see #5 and #6)
  - [ ] Implement counter of currently active strategies in tab label

# Code
Unsure if this can be retrieved via TheGraph. Prepare to also be able to add entries programmatically after successful transactions.

**Comment by andre-meyer** [comment]
Counter skipped for now. Add in later

**Comment by elena-zh** [comment]
Strategy overview page shows active and closed strategies currently. I move the task to Done.
However, a lot of features are not yet implemented: 
#98 - strategy details
#99 - closed strategy tab
- Strategies counters 
- Strategies filtering functionality

It would be nice to consider adding a 'pagination' feature to strategies lists (when a lot of them are displayed in the list)

The next bugs are found: 
#117 - some UI issues with Active strategies tab
#100 - pages are constantly reloaded each 10-30 ssec
