### ISSUE TITLE
Bug: Start price (price estimation) should be changeable 

### ISSUE THREAD

**Issue by andre-meyer** [gnosis/safe-cmm-app-react#44]
# Description
The start price should be working according to the design:
![image](https://user-images.githubusercontent.com/969493/92740787-4fe41d00-f37e-11ea-8688-380362083dec.png)

# To replicate
- [ ] Open "Deploy" screen
- [ ] Try to edit market priice

# Expected
Start-price should be editable.

# Notes
The above "market price" should be filled in if the user clicks a link showing the price. This is not necessary. **Automatically update the current price when the selected tokens change and allow manual editing.**

**Comment by elena-zh** [comment]
Verified. 
User is allowed to fill in and to edit a Start price. 
However, start price is not updated/changed when change a pair of tokens/swap tokens. Reported in  #86
