### ISSUE TITLE
Bug report - says I have insufficient funding

### ISSUE THREAD

**Issue by c3rnst** [gnosis/safe-cmm-app-react#46]

**Comment by c3rnst** [comment]
![Screenshot 2020-09-14 at 15 44 07](https://user-images.githubusercontent.com/34367524/93094003-a5cc0400-f6a1-11ea-8d7d-3236a28e31ae.png)

**Comment by c3rnst** [comment]
![Screenshot 2020-09-15 at 13 47 47](https://user-images.githubusercontent.com/34367524/93206711-22221e00-f75a-11ea-84dd-a4d9ad310974.png)
Same happening here in the case of GNO.

**Comment by elena-zh** [comment]
Tested with tokens with 2 and 6 decimals (and with 18 as well). Works fine.
