### ISSUE TITLE
Bug in price estimation

### ISSUE THREAD

**Issue by c3rnst** [gnosis/safe-cmm-app-react#51]
1) the price seems to be the other way around (please confirm this with Rafa). 

2) The price itself seems to be super far off 1inch prices. 

3) the price seems to be switching around (if the token pair remains the same and in the same way around)

**Comment by c3rnst** [comment]
![Screenshot 2020-09-15 at 12 12 37](https://user-images.githubusercontent.com/34367524/93204211-00269c80-f756-11ea-9c1a-113a10af5138.png)
![Screenshot 2020-09-15 at 12 13 09](https://user-images.githubusercontent.com/34367524/93204216-0157c980-f756-11ea-8cc3-43f1555d4450.png)
![Screenshot 2020-09-15 at 12 11 41](https://user-images.githubusercontent.com/34367524/93204226-06b51400-f756-11ea-84ac-06dfda3d2563.png)
![Screenshot 2020-09-15 at 12 12 15](https://user-images.githubusercontent.com/34367524/93204231-087ed780-f756-11ea-8948-24838c376b2d.png)

**Comment by elena-zh** [comment]
Verified. 
Prices are displayed in a correct order (Token B denominated in Token A), prices are not super far from 1inch. Prices are not changes for the same pair of tokens.
