### ISSUE TITLE
Bug report: Cannot claim (after having done the withdraw)

### ISSUE THREAD

**Issue by c3rnst** [gnosis/safe-cmm-app-react#52]
Claim of funds does not work, after having done the WithdrawRequest and waited sufficiently.

**Comment by c3rnst** [comment]
![Screenshot 2020-09-15 at 14 46 13](https://user-images.githubusercontent.com/34367524/93212188-8c3ec100-f762-11ea-98b1-809b14278318.png)

![Screenshot 2020-09-15 at 14 49 38](https://user-images.githubusercontent.com/34367524/93212289-b2fcf780-f762-11ea-9215-c4d6e063829a.png)


I did a withdraw request (signed it with all needed signatures). I waited long enough (a couple of hours), and I cannot claim it.

**Comment by elena-zh** [comment]
cannot test until the issue #71 is fixed (app version - 189412279 - 98816d8fae540d8fa2633bcbc0741dcadd62c4d0)

However, it worked fine on the 188875348 - b8a8e68008e31c5500395cb70ab755f3de6702ac app version

**Comment by elena-zh** [comment]
It appeared that withdraw is not working with USDc token in a strategy (#87).
So, I was able to request a withdraw and claim funds.
Move the issue to Done.
