### ISSUE TITLE
Bug report: Error does not update when I switch to other tokens

### ISSUE THREAD

**Issue by c3rnst** [gnosis/safe-cmm-app-react#54]
After I switch back to a different token pair that does not involve the one where it says insufficient balance, the error should update.

**Comment by c3rnst** [comment]
![Screenshot 2020-09-15 at 14 49 38](https://user-images.githubusercontent.com/34367524/93213841-a9748f00-f764-11ea-9acb-fdacc8675003.png)

**Comment by c3rnst** [comment]
![Screenshot 2020-09-15 at 14 10 29](https://user-images.githubusercontent.com/34367524/93213890-bd1ff580-f764-11ea-91cb-8724efb48187.png)

**Comment by andre-meyer** [comment]
@alfetopito Please ensure errors reset when you touch the form/change values.

**Comment by elena-zh** [comment]
Verified. Errors are reset when change tokens. 
Another issue (low priority) related to the error messages is found. Reported in #96

**Comment by alfetopito** [comment]
> Verified. Errors are reset when change tokens.

By this you mean you can reproduce OR the error is gone?

**Comment by elena-zh** [comment]
> > Verified. Errors are reset when change tokens.
> 
> By this you mean you can reproduce OR the error is gone?

I mean that the issue is gone, that is why I moved the task to Done. 
Anyway, I will write more descriptive comments. Sorry about that.

**Comment by alfetopito** [comment]
No worries, just wanted to make sure :)

And my bad, I did not notice it was moved to Done.
Will pay more attention to that from now on.
