### ISSUE TITLE
Bug report: withdrawn and claimed amounts are NOT back in the Mastersafe

### ISSUE THREAD

**Issue by c3rnst** [gnosis/safe-cmm-app-react#55]
After successfully having Withdrawn (requested) and claimed - from all signers needed, the funds do NOT appear back in the Mastersafe.

**Comment by c3rnst** [comment]
![Screenshot 2020-09-15 at 15 38 46](https://user-images.githubusercontent.com/34367524/93226660-db412200-f773-11ea-9b10-9a28e05befe4.png)

Attached a screenshots of the funds before and after, which is the same. I have tested this several times.

**Comment by elena-zh** [comment]
cannot test until the issue #71 is fixed (app version - 189412279 - 98816d8fae540d8fa2633bcbc0741dcadd62c4d0)

However, it worked fine on the 188875348 - b8a8e68008e31c5500395cb70ab755f3de6702ac app version

**Comment by elena-zh** [comment]
It appeared that withdraw is not working with USDc token in a strategy (#87). 
So, I was able to request a withdraw and claim and trace that amounts are returned back to the MasterSafe.
Move the issue to Done.
