### ISSUE TITLE
Bug report: Price flickering and price itself

### ISSUE THREAD

**Issue by c3rnst** [gnosis/safe-cmm-app-react#68]
THIS TICKET IS NOT ABOUT WHICH WAY AROUND THE PRICE IS DISPLAYED!

1) ETH is currently at 340 USD, so it seems a bit wrong. I checked this price also on 1inch, please see attached screenshot. 
2) please see video, the price keeps flickering when changing token sides OR when newly selecting tokens.

**Comment by c3rnst** [comment]
Cannot link a video, shared it here: https://gnosisinc.slack.com/archives/C015XA0NWAW/p1601026426062100

**Comment by alfetopito** [comment]
Sounds about right. Not the price, the behaviour.
I've seen it also but did not stop to investigate further.
Issue seems to be partially in the price fetching from the script (sometimes returning 1) and the price display on the UI (switching back and forth between a valid price and 1)

Is this a priority at this point?

**Comment by alfetopito** [comment]
Fixed by #81

**Comment by elena-zh** [comment]
I have verified the issue. Currently:

1. Prices after the 1st selection and the 1st switch of a Tokens pair are loaded, then
2. They are kept in cache for about 30 sec and are not flickering, then  are reloaded (if needed)
3. There is no a price of 1 in tokens' pairs
