### ISSUE TITLE
Bug report: twice the same token

### ISSUE THREAD

**Issue by c3rnst** [gnosis/safe-cmm-app-react#69]

**Comment by c3rnst** [comment]
<img width="255" alt="Screenshot 2020-09-25 at 10 22 40" src="https://user-images.githubusercontent.com/34367524/94266308-3f18d700-ff3a-11ea-861e-c672c3c321a3.png">

see OWL on this one.

**Comment by alfetopito** [comment]
Do you still see that?

**Comment by alfetopito** [comment]
Oops, closed by accident

**Comment by c3rnst** [comment]
No, I don't see it any longer.

**Comment by elena-zh** [comment]
Verified. The issue is not reproducible for me as well.
