### ISSUE TITLE
Feature: Implement ERC20 Input React Component

### ISSUE THREAD

**Issue by andre-meyer** [gnosis/safe-cmm-app-react#7]
# Description
To implement many of the views in the CMM-App, we need a re-useable component that allows us to specify "amounts" for ERC20 tokens.

![image](https://user-images.githubusercontent.com/969493/89986129-62364280-dc7c-11ea-87f3-fe0a40894818.png)
![image](https://user-images.githubusercontent.com/969493/89986145-6bbfaa80-dc7c-11ea-877a-b1aed5b2f5e9.png)

# Requirements
- [x] Implements a label
- [x] Only allows numeric inputs
- [ ] Uses validations to verify:
  - [ ] Not more than users balance
- [x] Can show users balance underneath input
- [ ] Implements "MAX" button to auto-fill the max investment
- [x] Implements tooltip/help that displays the `i`-info icon with helptext

# Code
For validations, feel free to re-use this: https://github.com/gnosis/conditional-markets-interface/blob/master/app/src/utils/validations.js

It's a common pattern I've used before to implement validations.

**Comment by elena-zh** [comment]
Components work fine. Here are some opened related issues: 
#106
#103 
#101 
#88
