### ISSUE TITLE
Correct calculations of brackets

### ISSUE THREAD

**Issue by c3rnst** [gnosis/safe-cmm-app-react#70]

**Comment by alfetopito** [comment]
Brackets calculation on the scripts: https://github.com/gnosis/dex-liquidity-provision/blob/525138d8feab5e85536b98a621e6f9abf537fcca/scripts/utils/trading_strategy_helpers.js#L329

I figured it out how it's calculated. Will implement it on the CMM app.

**Comment by elena-zh** [comment]
Verified. Works fine. 
Number of brackets and funding amounts/transfers are correct after a strategy deployment.
