### ISSUE TITLE
withdraw is not working

### ISSUE THREAD

**Issue by c3rnst** [gnosis/safe-cmm-app-react#71]

**Comment by elena-zh** [comment]
Withdraw is not working on the 189412279 - 98816d8fae540d8fa2633bcbc0741dcadd62c4d0 app version. Each time when I press on the Request Withdraw button I get 'Invalid number' error (tried with different pairs of tokens, multisig and a single owner options). 
![invalid price](https://user-images.githubusercontent.com/70885163/95721552-70540f80-0c7b-11eb-982c-7db26fe6b1c4.jpg)

I have to mention, that on Friday (09/10/2020) withdraw worked as expected.

**Comment by elena-zh** [comment]
> Withdraw is not working on the 189412279 - [98816d8](https://github.com/gnosis/safe-cmm-app-react/commit/98816d8fae540d8fa2633bcbc0741dcadd62c4d0) app version. Each time when I press on the Request Withdraw button I get 'Invalid number' error (tried with different pairs of tokens, multisig and a single owner options).
> ![invalid price](https://user-images.githubusercontent.com/70885163/95721552-70540f80-0c7b-11eb-982c-7db26fe6b1c4.jpg)
> 
> I have to mention, that on Friday (09/10/2020) withdraw worked as expected.
> 
> @andre-meyer , could you please take a look into the issue?

Just some notes: I can withdraw funds in cases when USDc token is not present in a strategy - reported in #87 
Move the task to Done, however, the feature is not stable enough: see additional issues #109 and #113
