### ISSUE TITLE
Bug report: yellow message flag does not update after being corrected

### ISSUE THREAD

**Issue by c3rnst** [gnosis/safe-cmm-app-react#83]

**Comment by c3rnst** [comment]
![Uploading Screenshot 2020-10-05 at 16.26.12.png…]()

**Comment by alfetopito** [comment]
> Uploading Screenshot 2020-10-05 at 16.26.12.png…

:point_up: screen shot is not there =P

Anyway, I know what you are talking about

That was a part of the initial validation setup, where I put an arbitrary rule for warnings just to test it out.
Whenever lowestPrice < 1 the warning is shown, only on that field.

Will be removed when dealing with warnings.
Unless this is a problem I can simply turn this off right now.
